// reactjs repo/src/components/atoms/DatePicker.tsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { use, useEffect, useRef, useState } from "react";

type DatePickerProps = {
  label?: string;
  value?: string;
  onChange: (value: string) => void;
  disabled?: boolean;
};

const days = ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"];

export default function DatePicker({
  label,
  value,
  onChange,
  disabled = false,
}: DatePickerProps) {
  const [open, setOpen] = useState(false);
  const [current, setCurrent] = useState<Date>(
    value ? new Date(value) : new Date(),
  );
  const [view, setView] = useState<"month" | "year">("month");
  const [position, setPosition] = useState({ top: 0, left: 0 });
  const [placement, setPlacement] = useState<"top" | "bottom">("bottom");
  const [yearBase, setYearBase] = useState<number>(
    (value ? new Date(value).getFullYear() : new Date().getFullYear()) - 6,
  );

  const containerRef = useRef<HTMLDivElement>(null);
  const buttonRef = useRef<HTMLButtonElement>(null);
  const popupRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;

    const handleClickOutside = (e: MouseEvent) => {
      if (
        containerRef.current &&
        !containerRef.current.contains(e.target as Node)
      ) {
        setOpen(false);
      }
    };

    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [open]);

  useEffect(() => {
    if (!open || !buttonRef.current) return;

    const buttonRect = buttonRef.current.getBoundingClientRect();
    const popupHeight = popupRef.current?.offsetHeight ?? 300;
    const viewportHeight = window.innerHeight;

    const spaceBelow = viewportHeight - buttonRect.bottom;
    const spaceAbove = buttonRect.top;

    if (spaceBelow < popupHeight && spaceAbove > popupHeight) {
      setPlacement("top");
      setPosition({
        top: buttonRect.top - popupHeight - 8,
        left: buttonRect.left,
      });
    } else {
      setPlacement("bottom");
      setPosition({
        top: buttonRect.bottom + 8,
        left: buttonRect.left,
      });
    }
  }, [open, view]);

  const year = current.getFullYear();
  const month = current.getMonth();
  const firstDay = new Date(year, month, 1).getDay();
  const daysInMonth = new Date(year, month + 1, 0).getDate();

  const selected =
    value && !isNaN(new Date(value).getTime())
      ? new Date(value).toDateString()
      : null;

  const years = Array.from({ length: 12 }, (_, i) => yearBase + i);

  return (
    <div ref={containerRef} className="w-full">
      {label && (
        <label className="mb-1 block text-sm font-medium text-gray-600">
          {label}
        </label>
      )}

      <button
        ref={buttonRef}
        type="button"
        disabled={disabled}
        onClick={() => setOpen((v) => !v)}
        className={`flex w-full items-center justify-between rounded-lg border px-3 py-2 text-sm
          ${
            disabled
              ? "cursor-not-allowed bg-gray-100 text-gray-400"
              : "bg-white text-gray-700 hover:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
          }`}
      >
        <span>
          {value ? new Date(value).toLocaleDateString() : "Select date"}
        </span>
        <FontAwesomeIcon icon={"calendar-days"} className="text-gray-400" />
      </button>

      {open && !disabled && (
        <div
          ref={popupRef}
          style={{ top: position.top, left: position.left }}
          className="fixed z-[9999] w-72 rounded-xl border bg-white p-4 shadow-xl"
        >
          <div className="mb-3 flex items-center justify-between">
            {view === "month" && (
              <>
                <button
                  onClick={() => setCurrent(new Date(year, month - 1, 1))}
                  className="rounded px-2 py-1 text-gray-500 hover:bg-gray-100"
                >
                  <FontAwesomeIcon icon={"angle-left"} />
                </button>

                <button
                  onClick={() => setView("year")}
                  className="text-sm font-semibold text-gray-700 hover:underline"
                >
                  {current.toLocaleString("default", {
                    month: "long",
                    year: "numeric",
                  })}
                </button>

                <button
                  onClick={() => setCurrent(new Date(year, month + 1, 1))}
                  className="rounded px-2 py-1 text-gray-500 hover:bg-gray-100"
                >
                  <FontAwesomeIcon icon={"angle-right"} />
                </button>
              </>
            )}
          </div>

          {view === "month" && (
            <>
              <div className="grid grid-cols-7 text-center text-xs text-gray-500">
                {days.map((d) => (
                  <div key={d}>{d}</div>
                ))}
              </div>

              <div className="mt-2 grid grid-cols-7 gap-1">
                {Array.from({ length: firstDay }).map((_, i) => (
                  <div key={i} />
                ))}

                {Array.from({ length: daysInMonth }).map((_, i) => {
                  const date = new Date(year, month, i + 1);
                  const isSelected = selected === date.toDateString();

                  return (
                    <button
                      key={i}
                      onClick={() => {
                        onChange(date.toUTCString());
                        setOpen(false);
                      }}
                      className={`rounded-md py-1 text-sm
                        ${
                          isSelected
                            ? "bg-blue-600 text-white"
                            : "hover:bg-blue-50"
                        }`}
                    >
                      {i + 1}
                    </button>
                  );
                })}
              </div>
            </>
          )}

          {view === "year" && (
            <div className="grid max-h-64 grid-cols-4 gap-2 overflow-auto">
              {years.map((y) => (
                <button
                  key={y}
                  onClick={() => {
                    setCurrent(new Date(y, month, 1));
                    setView("month");
                  }}
                  className={`rounded-md py-2 text-sm
                    ${
                      y === year ? "bg-blue-600 text-white" : "hover:bg-blue-50"
                    }`}
                >
                  {y}
                </button>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// vuejs repo/src/components/atoms/DatePicker.vue
<script setup lang="ts">
import { ref, computed, watch, nextTick, onBeforeUnmount } from 'vue'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

type Props = {
  label?: string
  value?: string
  disabled?: boolean
}

const props = defineProps<Props>()
const emit = defineEmits<{
  (e: 'change', value: string): void
}>()

const days = ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa']

const open = ref(false)
const view = ref<'month' | 'year'>('month')
const current = ref(props.value ? new Date(props.value) : new Date())

const position = ref({ top: 0, left: 0 })
const yearBase = ref(current.value.getFullYear() - 6)

const containerRef = ref<HTMLElement | null>(null)
const buttonRef = ref<HTMLElement | null>(null)
const popupRef = ref<HTMLElement | null>(null)

const year = computed(() => current.value.getFullYear())
const month = computed(() => current.value.getMonth())

const firstDay = computed(() => new Date(year.value, month.value, 1).getDay())
const daysInMonth = computed(() => new Date(year.value, month.value + 1, 0).getDate())

const selected = computed(() => (props.value ? new Date(props.value).toDateString() : null))

const years = computed(() => Array.from({ length: 12 }, (_, i) => yearBase.value + i))

function toggleOpen() {
  open.value = !open.value
}

function prevMonth() {
  current.value = new Date(year.value, month.value - 1, 1)
}

function nextMonth() {
  current.value = new Date(year.value, month.value + 1, 1)
}

function switchToYearView() {
  view.value = 'year'
}

function selectYear(y: number) {
  current.value = new Date(y, month.value, 1)
  view.value = 'month'
}

function selectDate(day: number) {
  const date = new Date(year.value, month.value, day)
  emit('change', date.toUTCString())
  open.value = false
}

function handleOutsideClick(e: MouseEvent) {
  if (containerRef.value && !containerRef.value.contains(e.target as Node)) {
    open.value = false
  }
}

async function updatePosition() {
  await nextTick()
  if (!buttonRef.value || !popupRef.value) return

  const rect = buttonRef.value.getBoundingClientRect()
  const height = popupRef.value.offsetHeight

  position.value = {
    top: rect.bottom + 8,
    left: rect.left,
  }

  if (window.innerHeight - rect.bottom < height) {
    position.value.top = rect.top - height - 8
  }
}

watch(open, (val) => {
  if (val) {
    document.addEventListener('mousedown', handleOutsideClick)
    updatePosition()
  } else {
    document.removeEventListener('mousedown', handleOutsideClick)
  }
})

watch(view, () => {
  if (open.value) updatePosition()
})

onBeforeUnmount(() => {
  document.removeEventListener('mousedown', handleOutsideClick)
})
</script>

<template>
  <div ref="containerRef" class="w-full">
    <label v-if="label" class="mb-1 block text-sm font-medium text-gray-600">
      {{ label }}
    </label>

    <button
      ref="buttonRef"
      type="button"
      :disabled="disabled"
      @click="toggleOpen"
      class="flex w-full items-center justify-between rounded-lg border px-3 py-2 text-sm"
      :class="
        disabled
          ? 'cursor-not-allowed bg-gray-100 text-gray-400'
          : 'bg-white text-gray-700 hover:border-blue-500 focus:ring-2 focus:ring-blue-500'
      "
    >
      <span>
        {{ value ? new Date(value).toLocaleDateString() : 'Select date' }}
      </span>
      <FontAwesomeIcon icon="calendar-days" class="text-gray-400" />
    </button>

    <div
      v-if="open && !disabled"
      ref="popupRef"
      :style="{ top: position.top + 'px', left: position.left + 'px' }"
      class="fixed z-[9999] w-72 rounded-xl border bg-white p-4 shadow-xl"
    >
      <div v-if="view === 'month'" class="mb-3 flex items-center justify-between">
        <button @click="prevMonth" class="rounded px-2 py-1 hover:bg-gray-100">‹</button>

        <button @click="switchToYearView" class="text-sm font-semibold hover:underline">
          {{ current.toLocaleString('default', { month: 'long', year: 'numeric' }) }}
        </button>

        <button @click="nextMonth" class="rounded px-2 py-1 hover:bg-gray-100">›</button>
      </div>

      <div v-if="view === 'month'">
        <div class="grid grid-cols-7 text-center text-xs text-gray-500">
          <div v-for="d in days" :key="d">{{ d }}</div>
        </div>

        <div class="mt-2 grid grid-cols-7 gap-1">
          <div v-for="i in firstDay" :key="'e' + i" />

          <button
            v-for="d in daysInMonth"
            :key="d"
            @click="selectDate(d)"
            class="rounded-md py-1 text-sm"
            :class="
              selected === new Date(year, month, d).toDateString()
                ? 'bg-blue-600 text-white'
                : 'hover:bg-blue-50'
            "
          >
            {{ d }}
          </button>
        </div>
      </div>

      <div v-if="view === 'year'" class="grid max-h-64 grid-cols-4 gap-2 overflow-auto">
        <button
          v-for="y in years"
          :key="y"
          @click="selectYear(y)"
          class="rounded-md py-2 text-sm"
          :class="y === year ? 'bg-blue-600 text-white' : 'hover:bg-blue-50'"
        >
          {{ y }}
        </button>
      </div>
    </div>
  </div>
</template>
