// reactjs repo/src/components/atoms/InputLabel.tsx
type InputProps = React.InputHTMLAttributes<HTMLInputElement> & {
  label?: string;
};

export function InputLabel({ label, className, ...props }: InputProps) {
  return (
    <div className="w-full flex flex-col gap-1">
      {label && (
        <label className="text-xs font-medium text-gray-500">{label}</label>
      )}
      <input
        {...props}
        className={`input w-full rounded-md border px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500 ${className}`}
      />
    </div>
  );
}

// vuejs repo/src/components/atoms/InputLabel.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue'

defineOptions({
  inheritAttrs: false,
})

const props = defineProps<{
  label?: string
  modelValue?: string
}>()

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void
}>()

const attrs = useAttrs()

const inputClass = computed(() => {
  const base =
    'input w-full rounded-md border px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500'
  const extra = (attrs.class as string) || ''
  return `${base} ${extra}`
})

const handleInput = (event: Event): void => {
  const target = event.target as HTMLInputElement
  emit('update:modelValue', target.value)
}
</script>

<template>
  <div class="w-full flex flex-col gap-1">
    <label v-if="props.label" class="text-xs font-medium text-gray-500">
      {{ props.label }}
    </label>

    <input v-bind="attrs" :class="inputClass" :value="props.modelValue" @input="handleInput" />
  </div>
</template>
