// reactjs repo/src/components/molecules/NotificationPromptCard.tsx
import Button from "@/components/atoms/Button";

type Props = {
  onAllow: () => void;
  onDismiss: () => void;
};

export const NotificationPromptCard = ({ onAllow, onDismiss }: Props) => {
  return (
    <div className="w-[360px] bg-white rounded-xl shadow-lg p-5 border border-gray-100">
      <h3 className="text-lg font-semibold text-gray-900">
        Enable notifications?
      </h3>

      <p className="mt-2 text-sm text-gray-600">
        Stay updated with important activity and messages.
      </p>

      <div className="mt-4 flex justify-end gap-2">
        <Button className="px-2" onClick={onDismiss}>
          Maybe later
        </Button>
        <Button className="px-2" onClick={onAllow}>
          Allow
        </Button>
      </div>
    </div>
  );
};

// vuejs repo/src/components/molecules/NotificationPromptCard.vue
<script setup lang="ts">
import Button from '@/components/atoms/ButtonBase.vue'

const emit = defineEmits<{
  (e: 'allow'): void
  (e: 'dismiss'): void
}>()
</script>

<template>
  <div class="w-[360px] rounded-xl border border-gray-100 bg-white p-5 shadow-lg">
    <h3 class="text-lg font-semibold text-gray-900">Enable notifications?</h3>

    <p class="mt-2 text-sm text-gray-600">Stay updated with important activity and messages.</p>

    <div class="mt-4 flex justify-end gap-2">
      <Button class="px-2" @click="emit('dismiss')"> Maybe later </Button>
      <Button class="px-2" @click="emit('allow')"> Allow </Button>
    </div>
  </div>
</template>
