// reactjs repo/src/components/molecules/UserGreeting.tsx
import { Avatar } from "@/components/atoms/Avatar";

type Props = {
  firstName: string;
  lastName: string;
  collapsed: boolean;
};

export function UserGreeting({ firstName, lastName, collapsed }: Props) {
  return (
    <div className="flex items-center gap-3 px-3 py-4">
      <Avatar firstName={firstName} lastname={lastName} />

      {!collapsed && (
        <div className="text-sm">
          <p className="text-gray-500">Hello</p>
          <p className="font-semibold truncate">{firstName + " " + lastName}</p>
        </div>
      )}
    </div>
  );
}

// vuejs repo/src/components/molecules/UserGreeting.vue
<script setup lang="ts">
import AvatarBase from '@/components/atoms/AvatarBase.vue'

type Props = {
  firstName: string
  lastName: string
  collapsed: boolean
}

defineProps<Props>()
</script>

<template>
  <div class="flex items-center gap-3 px-3 py-4">
    <AvatarBase :firstName="firstName" :lastName="lastName" />

    <div v-if="!collapsed" class="text-sm">
      <p class="text-gray-500">Hello</p>
      <p class="font-semibold truncate">{{ firstName }} {{ lastName }}</p>
    </div>
  </div>
</template>
